spring:
  application:
    name: discovery
---
spring:
  profiles: peer1
server:
  port: 1111
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server-peer2:1112/eureka/
---
spring:
  profiles: peer2
server:
  port: 1112
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server-peer1:1111/eureka/
